apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: starseed777/nodeapp:tagVersion
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: nodesecret